services:
  # MongoDB (для collector-service)
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongo_data:/data/db

  # Mongo Express (опционально)
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
      ME_CONFIG_MONGODB_URL:  "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongo:27017/"
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  # Collector Service
  collector:
    build:
      context: .
      dockerfile: ./collector-service/Dockerfile
    restart: always
    depends_on:
      - mongo
    environment:
      - APP_CONFIG=${APP_CONFIG}
      - JWT_SECRET=${JWT_SECRET}

  # Bot Service
  bot:
    build:
      context: .
      dockerfile: ./bot-service/Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - COLLECTOR_URL=${COLLECTOR_URL}
    restart: always

volumes:
  mongo_data: