services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  collector-service:
    build:
      context: .
      dockerfile: collector-service/Dockerfile
    container_name: collector-service
    env_file:
      - ./collector-service/.env
    ports:
      - "8080:8080"
    volumes:
      - ./collector-service/config.toml:/home/appuser/config.toml:ro
    depends_on:
      - mongo
    restart: on-failure

  bot-service:
    build:
      context: .
      dockerfile: bot-service/Dockerfile
    container_name: bot-service
    env_file:
      - ./bot-service/.env
    depends_on:
      - collector-service
      - redis
    restart: on-failure

volumes:
  redis_data:
  mongo_data:
