// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ShenokZlob/collector-ouphe/pkg/contracts/collector"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollectorClient creates a new instance of MockCollectorClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectorClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectorClient {
	mock := &MockCollectorClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollectorClient is an autogenerated mock type for the CollectorClient type
type MockCollectorClient struct {
	mock.Mock
}

type MockCollectorClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectorClient) EXPECT() *MockCollectorClient_Expecter {
	return &MockCollectorClient_Expecter{mock: &_m.Mock}
}

// CheckUser provides a mock function for the type MockCollectorClient
func (_mock *MockCollectorClient) CheckUser(reqData *collector.CheckUserRequest) (*collector.CheckUserResponse, error) {
	ret := _mock.Called(reqData)

	if len(ret) == 0 {
		panic("no return value specified for CheckUser")
	}

	var r0 *collector.CheckUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*collector.CheckUserRequest) (*collector.CheckUserResponse, error)); ok {
		return returnFunc(reqData)
	}
	if returnFunc, ok := ret.Get(0).(func(*collector.CheckUserRequest) *collector.CheckUserResponse); ok {
		r0 = returnFunc(reqData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.CheckUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*collector.CheckUserRequest) error); ok {
		r1 = returnFunc(reqData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectorClient_CheckUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUser'
type MockCollectorClient_CheckUser_Call struct {
	*mock.Call
}

// CheckUser is a helper method to define mock.On call
//   - reqData
func (_e *MockCollectorClient_Expecter) CheckUser(reqData interface{}) *MockCollectorClient_CheckUser_Call {
	return &MockCollectorClient_CheckUser_Call{Call: _e.mock.On("CheckUser", reqData)}
}

func (_c *MockCollectorClient_CheckUser_Call) Run(run func(reqData *collector.CheckUserRequest)) *MockCollectorClient_CheckUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*collector.CheckUserRequest))
	})
	return _c
}

func (_c *MockCollectorClient_CheckUser_Call) Return(checkUserResponse *collector.CheckUserResponse, err error) *MockCollectorClient_CheckUser_Call {
	_c.Call.Return(checkUserResponse, err)
	return _c
}

func (_c *MockCollectorClient_CheckUser_Call) RunAndReturn(run func(reqData *collector.CheckUserRequest) (*collector.CheckUserResponse, error)) *MockCollectorClient_CheckUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCollection provides a mock function for the type MockCollectorClient
func (_mock *MockCollectorClient) CreateCollection(reqData *collector.CreateCollectionRequest) (*collector.CreateCollectionResponse, error) {
	ret := _mock.Called(reqData)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollection")
	}

	var r0 *collector.CreateCollectionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*collector.CreateCollectionRequest) (*collector.CreateCollectionResponse, error)); ok {
		return returnFunc(reqData)
	}
	if returnFunc, ok := ret.Get(0).(func(*collector.CreateCollectionRequest) *collector.CreateCollectionResponse); ok {
		r0 = returnFunc(reqData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.CreateCollectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*collector.CreateCollectionRequest) error); ok {
		r1 = returnFunc(reqData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectorClient_CreateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollection'
type MockCollectorClient_CreateCollection_Call struct {
	*mock.Call
}

// CreateCollection is a helper method to define mock.On call
//   - reqData
func (_e *MockCollectorClient_Expecter) CreateCollection(reqData interface{}) *MockCollectorClient_CreateCollection_Call {
	return &MockCollectorClient_CreateCollection_Call{Call: _e.mock.On("CreateCollection", reqData)}
}

func (_c *MockCollectorClient_CreateCollection_Call) Run(run func(reqData *collector.CreateCollectionRequest)) *MockCollectorClient_CreateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*collector.CreateCollectionRequest))
	})
	return _c
}

func (_c *MockCollectorClient_CreateCollection_Call) Return(createCollectionResponse *collector.CreateCollectionResponse, err error) *MockCollectorClient_CreateCollection_Call {
	_c.Call.Return(createCollectionResponse, err)
	return _c
}

func (_c *MockCollectorClient_CreateCollection_Call) RunAndReturn(run func(reqData *collector.CreateCollectionRequest) (*collector.CreateCollectionResponse, error)) *MockCollectorClient_CreateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function for the type MockCollectorClient
func (_mock *MockCollectorClient) DeleteCollection(reqData *collector.DeleteCollectionRequest) error {
	ret := _mock.Called(reqData)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*collector.DeleteCollectionRequest) error); ok {
		r0 = returnFunc(reqData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollectorClient_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockCollectorClient_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - reqData
func (_e *MockCollectorClient_Expecter) DeleteCollection(reqData interface{}) *MockCollectorClient_DeleteCollection_Call {
	return &MockCollectorClient_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", reqData)}
}

func (_c *MockCollectorClient_DeleteCollection_Call) Run(run func(reqData *collector.DeleteCollectionRequest)) *MockCollectorClient_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*collector.DeleteCollectionRequest))
	})
	return _c
}

func (_c *MockCollectorClient_DeleteCollection_Call) Return(err error) *MockCollectorClient_DeleteCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollectorClient_DeleteCollection_Call) RunAndReturn(run func(reqData *collector.DeleteCollectionRequest) error) *MockCollectorClient_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithCollections provides a mock function for the type MockCollectorClient
func (_mock *MockCollectorClient) GetUserWithCollections(reqData *collector.GetCollectionsRequest) (*collector.GetCollectionsResponse, error) {
	ret := _mock.Called(reqData)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithCollections")
	}

	var r0 *collector.GetCollectionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*collector.GetCollectionsRequest) (*collector.GetCollectionsResponse, error)); ok {
		return returnFunc(reqData)
	}
	if returnFunc, ok := ret.Get(0).(func(*collector.GetCollectionsRequest) *collector.GetCollectionsResponse); ok {
		r0 = returnFunc(reqData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.GetCollectionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*collector.GetCollectionsRequest) error); ok {
		r1 = returnFunc(reqData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectorClient_GetUserWithCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithCollections'
type MockCollectorClient_GetUserWithCollections_Call struct {
	*mock.Call
}

// GetUserWithCollections is a helper method to define mock.On call
//   - reqData
func (_e *MockCollectorClient_Expecter) GetUserWithCollections(reqData interface{}) *MockCollectorClient_GetUserWithCollections_Call {
	return &MockCollectorClient_GetUserWithCollections_Call{Call: _e.mock.On("GetUserWithCollections", reqData)}
}

func (_c *MockCollectorClient_GetUserWithCollections_Call) Run(run func(reqData *collector.GetCollectionsRequest)) *MockCollectorClient_GetUserWithCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*collector.GetCollectionsRequest))
	})
	return _c
}

func (_c *MockCollectorClient_GetUserWithCollections_Call) Return(getCollectionsResponse *collector.GetCollectionsResponse, err error) *MockCollectorClient_GetUserWithCollections_Call {
	_c.Call.Return(getCollectionsResponse, err)
	return _c
}

func (_c *MockCollectorClient_GetUserWithCollections_Call) RunAndReturn(run func(reqData *collector.GetCollectionsRequest) (*collector.GetCollectionsResponse, error)) *MockCollectorClient_GetUserWithCollections_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockCollectorClient
func (_mock *MockCollectorClient) RegisterUser(reqData *collector.RegisterRequest) (*collector.RegisterResponse, error) {
	ret := _mock.Called(reqData)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *collector.RegisterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*collector.RegisterRequest) (*collector.RegisterResponse, error)); ok {
		return returnFunc(reqData)
	}
	if returnFunc, ok := ret.Get(0).(func(*collector.RegisterRequest) *collector.RegisterResponse); ok {
		r0 = returnFunc(reqData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.RegisterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*collector.RegisterRequest) error); ok {
		r1 = returnFunc(reqData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectorClient_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockCollectorClient_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - reqData
func (_e *MockCollectorClient_Expecter) RegisterUser(reqData interface{}) *MockCollectorClient_RegisterUser_Call {
	return &MockCollectorClient_RegisterUser_Call{Call: _e.mock.On("RegisterUser", reqData)}
}

func (_c *MockCollectorClient_RegisterUser_Call) Run(run func(reqData *collector.RegisterRequest)) *MockCollectorClient_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*collector.RegisterRequest))
	})
	return _c
}

func (_c *MockCollectorClient_RegisterUser_Call) Return(registerResponse *collector.RegisterResponse, err error) *MockCollectorClient_RegisterUser_Call {
	_c.Call.Return(registerResponse, err)
	return _c
}

func (_c *MockCollectorClient_RegisterUser_Call) RunAndReturn(run func(reqData *collector.RegisterRequest) (*collector.RegisterResponse, error)) *MockCollectorClient_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RenameCollection provides a mock function for the type MockCollectorClient
func (_mock *MockCollectorClient) RenameCollection(reqData *collector.RenameCollectionRequest) error {
	ret := _mock.Called(reqData)

	if len(ret) == 0 {
		panic("no return value specified for RenameCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*collector.RenameCollectionRequest) error); ok {
		r0 = returnFunc(reqData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollectorClient_RenameCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameCollection'
type MockCollectorClient_RenameCollection_Call struct {
	*mock.Call
}

// RenameCollection is a helper method to define mock.On call
//   - reqData
func (_e *MockCollectorClient_Expecter) RenameCollection(reqData interface{}) *MockCollectorClient_RenameCollection_Call {
	return &MockCollectorClient_RenameCollection_Call{Call: _e.mock.On("RenameCollection", reqData)}
}

func (_c *MockCollectorClient_RenameCollection_Call) Run(run func(reqData *collector.RenameCollectionRequest)) *MockCollectorClient_RenameCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*collector.RenameCollectionRequest))
	})
	return _c
}

func (_c *MockCollectorClient_RenameCollection_Call) Return(err error) *MockCollectorClient_RenameCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollectorClient_RenameCollection_Call) RunAndReturn(run func(reqData *collector.RenameCollectionRequest) error) *MockCollectorClient_RenameCollection_Call {
	_c.Call.Return(run)
	return _c
}
