# This file is used to configure the collector service

# HTTP server configuration
# The address and port on which the HTTP server will listen
[server_http]
host = "0.0.0.0:8080"

# MongoDB connection string
# The connection string to connect to the MongoDB database
# The default value is "mongodb://your_user:your_password@localhost:27017/?authSource=admin"
[database]
conn_string = "mongodb://root:example@mongo:27017"
