FROM golang:1.24-alpine AS base

WORKDIR /app

COPY pkg/ ./pkg/
COPY collector-service/go.mod collector-service/go.sum ./collector-service/

WORKDIR /app/collector-service
RUN go mod download

COPY collector-service/ .

RUN go build -o collector-service cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=base /app/collector-service/collector-service .
COPY --from=base /app/collector-service/config.toml .

ENV APP_CONFIG=config

EXPOSE 8080

CMD [ "./collector-service" ]