version: "3"

tasks:
  run:
    desc: "Run the bot locally with environment variables"
    cmds:
      - go mod tidy
      - go run ./cmd/main.go
    dir: .

  up:
    desc: "Launch docker-compose and app"
    cmds:
      - echo "Launch docker-compose"
      - docker-compose up -d
      - echo "Launch app"
      - |
        if ! go run cmd/main.go; then
          echo "Bot crush! Down containers..."
          docker-compose down
          exit 1
        fi
    silent: false

  down:
    desc: "Down all service"
    cmds:
      - echo "Down docker-compose..."
      - docker-compose down
      - echo "Down app"
      - pkill -f "go run cmd/main.go" || echo "The active proccess doesn't exist"
    silent: false

  docker-build:
    desc: "Build Docker image for bot-service"
    cmds:
      - docker build --rm . -t bot-service:latest
      - docker image prune -f

  docker-run:
    desc: "Run bot-service container with env from .env"
    cmds:
      - docker run --rm . --name bot-service-app --env-file .env bot-service:latest

  docker-rebuild:
    decs: "Rebuild image and run container"
    cmds:
      - task docker-build
      - task docker-run
